-- Grant necessary system views access
GRANT SELECT ON V$VERSION TO DEBEZIUM;
GRANT SELECT ON V$DATABASE TO DEBEZIUM;
GRANT SELECT ON V$INSTANCE TO DEBEZIUM;
GRANT SELECT ON V$LOG TO DEBEZIUM;
GRANT SELECT ON V$LOGFILE TO DEBEZIUM;
GRANT SELECT ON V$ARCHIVED_LOG TO DEBEZIUM;

-- Grant necessary packages
GRANT EXECUTE ON DBMS_LOGMNR TO DEBEZIUM;
GRANT EXECUTE ON DBMS_LOGMNR_D TO DEBEZIUM;

-- Already granted but let's ensure
GRANT SELECT ANY TABLE TO DEBEZIUM;
GRANT FLASHBACK ANY TABLE TO DEBEZIUM;

EXIT;
